spring:
  rabbitmq:
    username: username
    password: password
    port: 5672
    addresses: 39.97.243.43
    #confirm模式
    publisher-confirm-type: correlated
    #接收mq返回的确认消息
    publisher-returns: true


server:
  port: 8080
