spring:
  application:
    name: gateway-web
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有的请求
            allowedOrigins: "*" # 跨域处理
            allowedMethods: #
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: consumer
#          uri: http://localhost:8082 #指定要路由的服务 http://localhost:18081
          uri: lb://consumer #lb负载均衡,后面是微服务名称
          predicates: #路由断言,配置路由规则
            #- Host=zong.com** #所有的zong.com的请求都被路由到上面的uri,这里测试可以先修改windows的host文件如下,127.0.0.1 zong.com,
            # 访问http://zong.com:8001/brand/all,可看到正确路由
            - Path=/api/consumer/** #所有以/brand开头的请求,都路由到http://localhost:18081微服务
          filters:
            - StripPrefix=1 # 所有以/api/brand开头的请求,都路由到  http://localhost:18081微服务,且/api由gateway自动去除


management:
  endpoint:
    gateway:
      enabled: true

server:
  port: 8070