server:
  port: 8011
# 指定服务名称
spring:
  application:
    name: user-service-ribbon-client

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://root:123456@localhost:8005/eureka

