spring:
  redis:
    #redis数据库地址
    host: 127.0.0.1
    port: 6379
    timeout: 10001
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  application:
    name: product
#eureka:
#  instance:
#    prefer-ip-adress: true
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka

server:
  port: 8082
