server:
  port: 8001

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: localhost #server的实例名称
  client:
    fetch-registry: false #是否向注册中心注册自己
    register-with-eureka: false #false表示自己是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka # 监控页面
