server:
  port: 8003
spring:
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: replica2 #server的实例名称
  client:
    fetch-registry: true #是否向注册中心注册自己
    register-with-eureka: true #false表示自己是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka/ # 监控页面
