spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
mybatis:
  type-aliases-package: com.cloud.demo.entity

# 指定运行端口
server:
  port: 8010

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://root:123456@localhost:8005/eureka
management:
  endpoints:
    web:
      exposure:
        #暴露hystrix监控端点
        include: 'hystrix.stream'

