
spring:
  #freemarker
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  
  
  #mysql
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#spring-boot mybatis
mybatis:
  mapper-locations: classpath:com/demo/mapper/*.xml
  
    
    
      