server:
  port: 8014

spring:
  application:
    name: feign-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8005/eureka





