USE [master]
GO

/****** Object:  Database [DriverCradle]    Script Date: 11/17/2017 11:34:44 ******/
CREATE DATABASE [DriverCradle] ON  PRIMARY 
( NAME = N'DriverCradle', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS2008\MSSQL\DATA\DriverCradle.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DriverCradle_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS2008\MSSQL\DATA\DriverCradle_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DriverCradle] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DriverCradle].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DriverCradle] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DriverCradle] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DriverCradle] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DriverCradle] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DriverCradle] SET ARITHABORT OFF 
GO

ALTER DATABASE [DriverCradle] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DriverCradle] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DriverCradle] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DriverCradle] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DriverCradle] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DriverCradle] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DriverCradle] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DriverCradle] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DriverCradle] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DriverCradle] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DriverCradle] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DriverCradle] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DriverCradle] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DriverCradle] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DriverCradle] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DriverCradle] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DriverCradle] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DriverCradle] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DriverCradle] SET  READ_WRITE 
GO

ALTER DATABASE [DriverCradle] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DriverCradle] SET  MULTI_USER 
GO

ALTER DATABASE [DriverCradle] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DriverCradle] SET DB_CHAINING OFF 
GO

